### ISSUE TITLE
ERROR HTTP 429 

### ISSUE THREAD

**Issue by Kaleemullahqasim** [tasos-py/Search-Engines-Scraper#61] opened 2023-08-20 08:46 UTC
After a few pages of searching with the Google search engine, it started giving the 
"ERROR HTTP 429"
and once this happens, it just keeps giving the same error for upcoming queries from the list.

I understand it may be because of so many search queries being searched, but is there any fix to work around it?

**Comment by hcw5** [comment] 2023-09-23 14:27
use vpn or rotating proxies

**Comment by tasos-py** [comment] 2023-10-27 14:02
duplicate of #10

**Closed by tasos-py** 2023-10-27 14:02 UTC
